server:
  port: 8086

spring:
  application:
    #项目名称
    name: intelligent-luggage-locker-management-platform

  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/locker_management_platform?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&nullCatalogMeansCurrent=true
    username: root
    password: 20050401Fa
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 20050401Fa
      database: 0
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 1000
          max-idle: 1000
          min-idle: 1000
          max-wait: 10000ms